### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by IsFea** [w0nxyApex/Deadlock-Tweaks-config#5]
1. Can you make performance test before/after with you hardware? 
2. Mb you can attach screenshots low preset vs config preset? (Just for beauty repository)
3. It's work better with vulkan api?

**Comment by w0nxyApex** [comment]
1. Yes, I wanted to make a video explaining the settings and how to use them, and also briefly show the difference in my case. (I recorded it over the weekend but without sound -.-).
2. Maybe you can describe it more precisely.
3. I'm not sure, I use DirectX11, and in the .cfg file, the command for that is mat_dxlevel 110. But a friend told me that Vulkan gives him better performance. You might just have to try it out for yourself :)
I'm glad you're interested.
