### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by haohaoya12** [w0nxyApex/Deadlock-Tweaks-config#8]
本人低端电脑，i58400，1060 6g，在使用后添加了很多附加项，首先想要自己弄好，需要很多的调整，然后发现最后的设置里变成了fsr默认，画质其实提升了，但是帧数降下来了，当我改成fsr2的时候所带来的帧数表现其实更好一些，画质也相差无几，所以我就没有在使用它了，但我依然希望可以支持优化。感谢

**Comment by w0nxyApex** [comment]
好的，希望它能有所帮助。不同计算机之间的差异总是略有不同，尤其是由于硬件的原因。该指南主要关注CPU性能，有时需要GPU支持（这是用Google翻译的，希望您理解）
